### PR TITLE
Root prefix pprint package to avoid hygiene problems

### PR DESCRIPTION
**Pull request by olafurpg**

### CODE REVIEW

**Comment by olafurpg** [comment]
Scala Native test failure is fixed by https://github.com/lihaoyi/PPrint/pull/23

**Comment by olafurpg** [comment]
@lihaoyi any chance you would be open to give me collaborator rights for this repo? I would like to publish pprint for 2.13 :)

**Comment by lihaoyi** [comment]
done

**Comment by olafurpg** [comment]
Thanks!

**Pull request merged**
